#!/data/data/com.termux/files/usr/bin/bash

clear

pkg update -y && pkg upgrade -y

pkg install -y python curl

pip install -U pip
pip install -U discord.py requests aiohttp

DOWNLOAD_DIR="/storage/emulated/0/Download"
BOOT_DIR="$HOME/.termux/boot"

TOKEN_FILE="$DOWNLOAD_DIR/bot_token.txt"
NAME_FILE="$DOWNLOAD_DIR/name.txt"

RUN_FILE="$BOOT_DIR/run_bot.sh"

mkdir -p "$DOWNLOAD_DIR"
mkdir -p "$BOOT_DIR"

clear

echo "=============================="
echo "      INSTALL BOT AUTO"
echo "=============================="
echo ""

read -p "Token : " BOT_TOKEN
read -p "Tên máy : " MACHINE_NAME

echo "$BOT_TOKEN" > "$TOKEN_FILE"
echo "$MACHINE_NAME" > "$NAME_FILE"

cat > "$RUN_FILE" << EOF
#!/data/data/com.termux/files/usr/bin/bash

termux-wake-lock

cd /storage/emulated/0/Download

curl -Ls \
https://raw.githubusercontent.com/mewAI36/bot-discord/refs/heads/main/bot.py \
-o bot.py

python bot.py
EOF

chmod +x "$RUN_FILE"

clear

echo "=============================="
echo "     INSTALL THÀNH CÔNG"
echo "=============================="
echo ""

echo "Token : $TOKEN_FILE"
echo "Tên máy : $NAME_FILE"
echo "Auto boot : $RUN_FILE"

echo ""
echo "Đang tải & chạy bot..."
echo ""

bash "$RUN_FILE"
